### ISSUE TITLE
'base Command' is not defined

### ISSUE THREAD

**Issue by hfpro** [ipc-sim/IDP#1]
an error occurs when running the script

file "/home/my/Downloads/IDP-main/Projects/FEMShell/batch.py", line 5, in <module>
    base Command += 'export MKL_NUM_THREADS=' + numThreads + '\export OMP_NUM_THREADS=' + numThreads + '\export VECLIB_MAXIMUM_THREADS=' + numThreads + '\n'
NameError: name 'base Command' is not defined

**Comment by liminchen** [comment]
solved with 6ad09f8e6b907b0afdff1be583abce21c4986aa1
